spring:
  cloud:
    loadbalancer:
      cache:
        enabled: false
      retry:
        enabled: false
    openfeign:
      httpclient:
        enabled: false
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  main:
    banner-mode: off